import { StyleSheet } from 'react-native';

export const stylesTabBar = StyleSheet.create({
  barWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: 'transparent',
    alignItems: 'center',
    paddingBottom: 0,
  },
  barContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%', // Change to less than 100% for floating effect
    marginHorizontal: 0,
    marginBottom: 12,
    marginTop: 4,
    borderRadius: 32,
    backgroundColor: '#F7F5F2',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
    elevation: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 64,
  },
  barContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 32,
    backgroundColor: '#F7F5F2',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
    elevation: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 64,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
  },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginBottom: 2,
  },
  tabLabel: {
    fontSize: 13,
    marginTop: 2,
    fontFamily: 'System',
  },
});
